### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by cvzi** [ipcjs/ScreenshotTile#3]
Hi, can I publish this app myself, if I make changes to the source code?

**Comment by ipcjs** [comment]
I don't want you to do this.

**Comment by cvzi** [comment]
Could you add a license? Then I would like to use some of your code to make a new app

**Comment by ipcjs** [comment]
908b0ed648e5ef5a89b502bc3991c73e7398380c

**Comment by cvzi** [comment]
thank you

**Comment by cvzi** [comment]
Hey, sorry to bother you again, I have another question:
if I rewrote your app, so it would work without root, would you then be okay, if I publish it again?
