### ISSUE TITLE
Icon does not appear in the tiles section on MIUI

### ISSUE THREAD

**Issue by dredkin** [ipcjs/ScreenshotTile#6]
I have a Mi Max 3 with MIUI 10 installed. MIUI 10 has it's own upper drawer of switches and so I cannot run the app. Are there any other way to run the app?
Haven't you thought the permanent notification we could tap to instead of a "tile"?

**Comment by ipcjs** [comment]
MIUI itself has a screenshot tile, so there is no need to install the app.

**Comment by dredkin** [comment]
Oh, I see. So your app uses the standard Android screencap API? 
I thought that if it asks for root remissions it uses root-enabled screen capture mechanics.

If it's a standard, I think you can close the issue.

**Comment by ipcjs** [comment]
Yes, the app just execute `input keyevent 120`.
https://github.com/ipcjs/ScreenshotTile/blob/master/app/src/main/java/com/github/ipcjs/screenshottile/Utils.java#L47
