### ISSUE TITLE
Android 12 Home Button

### ISSUE THREAD

**Issue by rjm831** [ipcjs/ScreenshotTile#9]
Using a Samsung Tab A7.  App has worked flawlessly until Samsung upgraded me to Android 12.  Now when I hit the home button for a screenshot the display becomes a solid color and freezes.  All settings are proper I believe, and I don't know if this bug is due to Android 12 or due to recent app updates.  Don't have root privileges but be happy to provide any log I can give.

**Comment by cvzi** [comment]
Since you said home button and no root, I believe your using my app "Screenshot Tile [No root]" https://github.com/cvzi/ScreenshotTile which is a fork of this app. If so, could you open an issue there please.
